//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertise
    {
        public int No { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string AdTitle { get; set; }
        public string AdContant { get; set; }
        public string AdPicturePath { get; set; }
        public Nullable<int> AdstatueId { get; set; }
    
        public virtual Administarator Administarator { get; set; }
        public virtual AdvertiseStatue AdvertiseStatue { get; set; }
    }
}
